classDiagram
    class Collection {
        -name : String
        -products : Products[]

        +getName() : String
        +setName(name : String)
        +getProducts() : Products[]
        +setProducts(products : Products[])
        +addProduct(product : Product)
        +removeProduct(product : Product)
    }
